data: 
  type: DAIR-V2X

  # if the dataset is DAIR-V2X
  data_root_path: /mnt/c/Users/10612/Downloads/cooperative_data/cooperative-vehicle-infrastructure
  
  # data_info_path: /home/massimo/vehicle_infrastructure_calibration/v2x_calib/dataset_division/easy_data_info.json
  data_info_path: /home/massimo/vehicle_infrastructure_calibration/v2x_calib/dataset_division/hard_data_info.json
  # data_info_path: ./data/cooperative-vehicle-infrastructure/cooperative/selected_data_info.json


evaluation:
  rot_thd: 5 # the error between the estimated pose and GT shouldn't exceed 5 degrees
  trans_thd: 2 # the error between the estimated pose and GT shouldn't exceed 2 meters

infra:
  fpfh:
    voxel_size: 1.0 # meter
    radius_normal: 2.0 # meter, for normal estimation
    radius_feature: 5.0 # meter, for feature estimation

vehicle:
  fpfh:
    voxel_size: 0.5 # meter/home/massimo/miniconda3/envs/teaser_test/bin/python /home/massimo/vehicle_infrastructure_calibration/benchmark/hkust_lidar_global_registration_benchmark.py
    radius_normal: 1.0 # meter, for normal estimation
    radius_feature: 2.5 # meter, for feature estimation

# "FGR" or "QUATRO"
rotation_estimation_algorithm: "GNC_TLS"
# rotation_estimation_algorithm: "FGR"
# rotation_estimation_algorithm: "QUATRO"

teaser:
  noise_bound: 0.4 # meter

